PaGlobal_TradeMyBasket_All = {
  _ui = {
    _txt_Title = nil,
    _btn_Close_Pc = nil,
    _list2_MyBasket = nil,
    _list2_MyBasketContent = nil,
    _stc_SlotBg_Template = nil,
    _stc_ItemIconBg_Template = nil,
    _txt_ItemName_Template = nil,
    _txt_ItemPrice_Template = nil,
    _btn_ItemCount_Template = nil,
    _btn_ClearItem_Template = nil,
    _list2_MyItem = nil,
    _list2_MyItemContent = nil,
    _stc_MyItemSlotBg_Template = nil,
    _stc_MyItemItemIconBg_Template = nil,
    _txt_MyItemItemName_Template = nil,
    _txt_MyItemItemPrice_Template = nil,
    _btn_MyItemItemSell_Template = nil,
    _txt_MyItemPeriod_Template = nil,
    _txt_MyItemProfit_Template = nil,
    _txt_MyItemOrigin_Template = nil,
    _txt_MyItemDistanceBonus_Template = nil,
    _txt_MyItemTradeGame_Template = nil,
    _stc_InvenBg = nil,
    _rdo_Inven = nil,
    _rdo_LandVehicle = nil,
    _rdo_SeaVehicle = nil,
    _txt_InvenWeight = nil,
    _txt_InvenSlotCount = nil,
    _txt_LandWeight = nil,
    _txt_LandSlotCount = nil,
    _txt_SeaWeight = nil,
    _txt_SeaSlotCount = nil,
    _stc_MoneyBg = nil,
    _txt_NeedMoney = nil,
    _stc_NeedMoney = nil,
    _stc_Money = nil,
    _txt_Money = nil,
    _btn_BuyAll_PC = nil,
    _btn_ClearALL_PC = nil,
    _btn_TradeGame_PC = nil,
    _btn_SellALL_PC = nil,
    _txt_NoItem = nil,
    _stc_KeyGuide_A = nil,
    _stc_KeyGuide_B = nil,
    _stc_KeyGuide_X = nil,
    _stc_KeyGuide_Y = nil,
    _keyGuideTable = {}
  },
  slotConfig = {
    createIcon = true,
    createBorder = true,
    createCount = true,
    createCash = true
  },
  _currentCartItemTable = {},
  _cachedItemKey = {},
  _currentSlotCount = nil,
  _vehicleStatus = nil,
  _ENUM_INVENTORY = 0,
  _ENUM_LAND_VEHICLE = 1,
  _ENUM_SEA_VEHICLE = 2,
  _ENUM_NO_VEHICLE = -1,
  _ENUM_ALL_VEHICLE = 5,
  _ENUM_TAB_BUY = 0,
  _ENUM_TAB_SELL = 1,
  _OriginKeyGuide_PosX = 0,
  _CONST_CALCULATE_PERCENT_VALUE = 10000,
  _LIMITED_SELLMONEY = 1000000000,
  _buyRequest = false,
  _isNoLinkedNodeOne = nil,
  _myItemTotalCount = -1,
  _myItemDataTable = {},
  _realPriceList = {},
  _list2ScrollData = {_scrollPos = 0, _currentIdx = 0},
  _tooltipType = {
    [0] = "tradeMarket_Buy",
    [1] = "tradeMarket_Sell",
    [2] = "tradeMarket_VehicleSell",
    [3] = "tradeMarket_ShipSell"
  },
  _myItemSlotTable = {},
  _totalPrice = nil,
  _totalWeight = nil,
  _totalSlot = nil,
  _initialize = false,
  _isConsole = false,
  _sellData = nil,
  _hasSellItem = false,
  _currShopType = nil
}
runLua("UI_Data/Script/Window/TradeMarket/Panel_Dialog_Trade_MyBasket_All_1.lua")
runLua("UI_Data/Script/Window/TradeMarket/Panel_Dialog_Trade_MyBasket_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_TradeMyBasketAll_init")
function FromClient_TradeMyBasketAll_init()
  PaGlobal_TradeMyBasket_All:initialize()
end
