local Mindamage = 0
local Maxdamage = 0
local SumCountDamage = 0
function StartQAequipArmor()
  ToClient_qaDebugDamage(0, 1, 1)
end
function StartQASkillUse(SkillQaNumber)
  ToClient_qaDebugDamage(1, SkillQaNumber)
end
function StartQASkillUseGuardian(ST)
  local selfPlayer = getSelfPlayer()
  if nil == selfPlayer then
    return
  end
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5000)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5001)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5002)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5003)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5004)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5005)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5006)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5007)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5008)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5009)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5010)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5011)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5012)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5013)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5014)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5015)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5037)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5038)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5039)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5040)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5105)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5106)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5107)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5108)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5109)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5120)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5121)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5122)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5123)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5114)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5115)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5116)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5117)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5110)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5111)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5112)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5113)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5065)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5066)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5067)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5139)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5140)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5141)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5045)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5046)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5047)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5048)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5049)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5050)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5041)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5042)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5043)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5044)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5097)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5098)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5099)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5100)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5101)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5102)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5094)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5095)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5096)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5060)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5061)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5062)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5078)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5079)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5080)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5081)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5068)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5069)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5070)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5071)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5072)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5054)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5055)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5056)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5057)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5058)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5059)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5087)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5088)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5089)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5090)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5091)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5142)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5143)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5144)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5145)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5073)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5074)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5075)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5076)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5077)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5082)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5083)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5084)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5085)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5086)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5126)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5127)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5128)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5129)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5130)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5147)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5148)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5149)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5150)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5151)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5178)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5154)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5155)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5156)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5157)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5158)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5159)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5160)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5161)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5169)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5170)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5171)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5172)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5162)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5163)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5164)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5165)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5166)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5167)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5175)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5176)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5177)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5168)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5174)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5173)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5179)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5180)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5181)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5183)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5188)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5189)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5190)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5191)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5192)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5193)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5194)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5195)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5196)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5197)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5198)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5199)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5200)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5201)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5202)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5203)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5204)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5205)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5206)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5207)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5208)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5209)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5210)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5211)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5212)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5214)
  luaTimer_AddEvent(GuardianSkill, 0, false, 0, ST, 5215)
  chatting_sendMessage("", "Guardian SkillTest End(PVP)", CppEnums.ChatType.Private)
end
function GuardianSkill(ST, SkillNo)
  if ST == 1 then
    ToClient_qaDebugDamage(1, SkillNo)
  elseif ST == 2 then
  end
end
