PaGlobal_ServantInfo_All = {
  _ui = {
    _stc_infoBg = nil,
    _txt_Name = nil,
    _icon_ServantGender = nil,
    _icon_SwiftHorse = nil,
    _txt_Tier = nil,
    _stc_ExpBg = nil,
    _txt_ExpTitle = nil,
    _txt_ExpValue = nil,
    _stc_ExpProgressBg = nil,
    _prog2_Exp = nil,
    _prog2_Exp_Head = nil,
    _stc_HpBg = nil,
    _txt_HpTitle = nil,
    _txt_HpValue = nil,
    _stc_HpProgressBg = nil,
    _prog2_Hp = nil,
    _prog2_Hp_Head = nil,
    _stc_StaminaBg = nil,
    _stc_StaminaProgressBg = nil,
    _txt_StatminaTitle = nil,
    _txt_StatminaValue = nil,
    _prog2_Stamina = nil,
    _prog2_Stamina_Head = nil,
    _stc_WeightBg = nil,
    _txt_WeightTitle = nil,
    _txt_WeightValue = nil,
    _stc_WeightProgressBg = nil,
    _prog2_Weight = nil,
    _prog2_Weight_Head = nil,
    _stc_StatBg = nil,
    _txt_SpeedTitle = nil,
    _txt_SpeedValue = nil,
    _txt_CorneringTitle = nil,
    _txt_CorneringValue = nil,
    _txt_AccelrationTitle = nil,
    _txt_AccelrationValue = nil,
    _txt_BreakTitle = nil,
    _txt_BreakValue = nil,
    _txt_DeadTitle = nil,
    _txt_DeadValue = nil,
    _txt_MatingTitle = nil,
    _txt_MatingValue = nil,
    _txt_LeftLifeTitle = nil,
    _txt_LeftLifeValue = nil,
    _txt_ImprintTitle = nil,
    _txt_ImprintValue = nil,
    _stc_SkillBg = nil,
    _txt_SkillBgTitle = nil,
    _list2_Skill = nil,
    _list2_Content = nil,
    _list2_SkillSlotBg = nil,
    _list2_list2_ExpBg = nil,
    _list2_Circle_Prog2_Exp = nil,
    _list2_stc_SkillIcon = nil,
    _list2_txt_SkillExpPerCent = nil,
    _list2_txt_SkillName = nil,
    _list2_txt_SkillCommand = nil,
    _list2_VertiScroll = nil,
    _list2_VertiScroll_Up = nil,
    _list2_VertiScroll_Down = nil,
    _list2_VertiScroll_Ctrl = nil,
    _list2_HoriScroll = nil,
    _list2_HoriScroll_Up = nil,
    _list2_HoriScroll_Down = nil,
    _list2_HoriScroll_Ctrl = nil,
    _btn_SkillManagerBg = nil,
    _btn_SkillManager = nil,
    _stc_StautsArea = nil,
    _txt_StatusTitle = nil,
    _btn_Immediate = nil,
    _btn_GetHorse = nil,
    _stc_ConsoleHighlight = nil
  },
  _ADDPOSY = 30,
  _STATBGGAP = 45,
  _OriginSkillBgPosY = nil,
  _OriginSkillBgSizeY = nil,
  _OriginList2SizeY = nil,
  _OriginPanelSizeY = nil,
  _ENUM_NPC_TYPE = {
    _LAND = 0,
    _GUILD_LAND = 1,
    _SEA = 2,
    _GUILD_SEA = 3
  },
  _isContentsTrainingEnable = ToClient_IsContentsGroupOpen("60"),
  _isContentsTrainingAllEnable = ToClient_IsContentsGroupOpen("452"),
  _isContentsStallionEnable = ToClient_IsContentsGroupOpen("243"),
  _isContentsNineTierEnable = ToClient_IsContentsGroupOpen("80"),
  _currentNpcType = nil,
  _currentSlotType = nil,
  _currentVehicleIndexNo = nil,
  _currentVehicleNo = nil,
  _currentServantInfo = nil,
  _currentSkillListData = {_pos = nil, _index = nil},
  _statCount = 1,
  _skillIdxTable = {},
  _isConsole = false,
  _initailize = false
}
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantInfo_All_1.lua")
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantInfo_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_ServantInfo_All_Init")
function FromClient_ServantInfo_All_Init()
  PaGlobal_ServantInfo_All:initialize()
end
