PaGlobal_ServantMarket_All = {
  _ui = {
    _stc_TitleBg = nil,
    _btn_Question_PC = nil,
    _btn_Close_PC = nil,
    _stc_TabGroup = nil,
    _rdo_Tab_MarketList = nil,
    _rdo_Tab_MyRegistList = nil,
    _stc_SelectedLine = nil,
    _stc_KeyGuide_LT = nil,
    _stc_KeyGuide_RT = nil,
    _stc_PageBg = nil,
    _txt_PageValue = nil,
    _btn_PageLeft_PC = nil,
    _btn_PageRight_PC = nil,
    _stc_PageLeft_Console = nil,
    _stc_PageRight_Console = nil,
    _stc_SortBg_PC_UI = nil,
    _stc_DiscountRate = nil,
    _stc_ComboBox_TierTitle = nil,
    _stc_ComboBox_GenderTitle = nil,
    _stc_ComboBox_SkillTitle = nil,
    _stc_ComboBox_Tier = nil,
    _stc_ComboBox_TierList = nil,
    _scroll_ComboBox_Tier = nil,
    _scrollUp_ComboBox_Tier = nil,
    _scrollDown_ComboBox_Tier = nil,
    _scrollCtrl_ComboBox_Tier = nil,
    _stc_ComboBox_Tier_BackStatic = nil,
    _stc_ComboBox_Skill = nil,
    _stc_ComboBox_SkillList = nil,
    _scroll_ComboBox_Skill = nil,
    _scrollUp_ComboBox_SKill = nil,
    _scrollDown_ComboBox_SKill = nil,
    _scrollCtrl_ComboBox_SKill = nil,
    _stc_ComboBox_Skill_BackStatic = nil,
    _stc_ComboBox_Gender = nil,
    _stc_ComboBox_GenderList = nil,
    _scroll_ComboBox_Gender = nil,
    _scrollUp_ComboBox_Gender = nil,
    _scrollDown_ComboBox_Gender = nil,
    _scrollCtrl_ComboBox_Gender = nil,
    _stc_ComboBox_Gender_BackStatic = nil,
    _btn_Reload_PC = nil,
    _stc_SortBg_ConsoleUI = nil,
    _txt_FilterTitle = nil,
    _txt_FilterValue = nil,
    _txt_InvenTitle = nil,
    _txt_Inven = nil,
    _txt_WareTitle = nil,
    _txt_Ware = nil,
    _stc_SkillTooltip = nil,
    _btn_SkillTooltip_Close_PC = nil,
    _stc_SkillTooltip_KeyGuide_B = nil,
    _stc_Bottom_KeyGuides = nil,
    _stc_KeyGuide_A = nil,
    _stc_KeyGuide_B = nil,
    _stc_KeyGuide_X = nil,
    _stc_KeyGuide_RS = nil,
    _stc_KeyGuide_Y = nil,
    _stc_KeyGuide_Y_Tooltip = nil,
    _servantSlot = {},
    _keyguides = {}
  },
  _string_ServantTier = {
    [0] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_GENERATION_FILTER_0"),
    [1] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_GENERATION_FILTER_1"),
    [2] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_GENERATION_FILTER_2"),
    [3] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_GENERATION_FILTER_3"),
    [4] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_GENERATION_FILTER_4"),
    [5] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_GENERATION_FILTER_5"),
    [6] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_GENERATION_FILTER_6"),
    [7] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_GENERATION_FILTER_7"),
    [8] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_GENERATION_FILTER_8"),
    [9] = PAGetString(Defines.StringSheet_GAME, "LUA_SERVANT_TEXT_TIER9")
  },
  _sexFilterString = {
    [0] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_SEXFILTER_0"),
    [1] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_SEXFILTER_1"),
    [2] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_SEXFILTER_2")
  },
  _isContentsStallionEnable = ToClient_IsContentsGroupOpen("243"),
  _isContentsNineTierEnable = ToClient_IsContentsGroupOpen("80"),
  _isContentsEightTierEnable = ToClient_IsContentsGroupOpen("29"),
  _selectSlotNo = nil,
  _selectPage = 0,
  _selectMaxPage = 0,
  _isTabMyRegister = nil,
  _skillFilterSelectIndex = {},
  _isFromNpc = true,
  _auctionInfo = nil,
  _selectIndex = 0,
  _MAXSLOTCOUNT = 4,
  _TIERCOUNT = 9,
  _SKILLCOUNT = 56,
  _isConsole = false,
  _initailize = false
}
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantMarket_All_1.lua")
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantMarket_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_ServantMarket_All_Init")
function FromClient_ServantMarket_All_Init()
  PaGlobal_ServantMarket_All:initialize()
end
