PaGlobal_ServantSwiftTraining_All = {
  _ui = {
    _txt_Title = nil,
    _btn_Close_PC = nil,
    _stc_Bg = nil,
    _stc_MainBg = nil,
    _txt_TopDesc = nil,
    _txt_Stack = nil,
    _btn_Train = nil,
    _stc_SkillBg = nil,
    _stc_EleganceBg = nil,
    _stc_StaminaBg = nil,
    _stc_CrogdaloSlot = nil,
    _txt_CrogdaloCount = nil,
    _icon_Skill = nil,
    _stc_ProgressBg_Skill = nil,
    _prog2_Skill = nil,
    _prog2_Skill_Head = nil,
    _stc_Skill_Material = nil,
    _txt_Skill_Percent = nil,
    _txt_Skill_Title = nil,
    _icon_Elegance = nil,
    _stc_ProgressBg_Elegance = nil,
    _prog2_Elegance = nil,
    _prog2_Elegance_Head = nil,
    _stc_Elegance_Material = nil,
    _txt_Elegance_Percent = nil,
    _txt_Elegance_Title = nil,
    _icon_Stamina = nil,
    _stc_ProgressBg_Stamina = nil,
    _prog2_Stamina = nil,
    _prog2_Stamina_Head = nil,
    _stc_Stamina_Material = nil,
    _txt_Stamina_Percent = nil,
    _txt_Stamina_Percent = nil,
    _txt_Stamina_Title = nil,
    _btn_Guide_Pc = nil,
    _icon_Guide = nil,
    _txt_TotalPercent = nil,
    _stc_ButtonBg = nil,
    _btn_Check_Cron = nil,
    _txt_Count_Cron = nil,
    _btn_Try_Swift = nil,
    _list_NeedItemList = nil,
    _stc_toolTipControl = nil,
    _stc_CronTooltipBg = nil,
    _txt_CronTooltip = nil,
    _stc_DescTooltipBg = nil,
    _txt_DescTooltip = nil,
    _stc_Console_KeyGuides = nil,
    _stc_KeyGuide_A = nil,
    _stc_KeyGuide_B = nil,
    _stc_KeyGuide_X = nil,
    _stc_KeyGuide_Y = nil
  },
  slotConfig = {
    createIcon = true,
    createBorder = true,
    createCount = true
  },
  _cronStoneInfo = {
    _cronStoneSlotNo = -1,
    _isEnableCronStone = false,
    _cronStoneCount = 0
  },
  _crogdaloInfo = {
    _crogdaloSlotNo = -1,
    _isEnableCrogdalo = false,
    _crogdaloCount = 0
  },
  _enum_BtnType = {
    _NOTCLICK = -1,
    _TRAINING = 0,
    _SWIFT = 1
  },
  _currentServentNo = nil,
  _over_SlotEffect = nil,
  _ORIGIN_SWIFTGUIDEBG_SIZEY = nil,
  _ORIGIN_CRONGUIDEBG_SIZEY = nil,
  _isGuideShow = false,
  _currentSkillBg = nil,
  _slotCount = 3,
  _awakenExpCount = 0,
  _effectControl = {},
  _controlCount = 0,
  _awakenDoing = false,
  _isButtonClick = -1,
  _effectType = 0,
  _elapsedTime = 0,
  _frame = 0,
  _trainingSlot = {},
  _materialItemSlot = {},
  _itemIconGroup = nil,
  _itemTotalCount = 0,
  _itemSlotList = {},
  _isSkillIconSet = false,
  _skillExpCount = {},
  _isConsole = false,
  _initailize = false,
  SLOTBGSIZEY = 45,
  _originToolTipControlSizeY = 0
}
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantSwiftTraining_All_1.lua")
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantSwiftTraining_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_ServantSwiftTraining_All_Init")
function FromClient_ServantSwiftTraining_All_Init()
  PaGlobal_ServantSwiftTraining_All:initialize()
end
