PaGlobal_ServantExchange_All = {
  _ui = {
    _txt_Title = nil,
    _btn_Close_PC = nil,
    _btn_Question_PC = nil,
    _stc_Bg = nil,
    _stc_Exchange_Bg = nil,
    _txt_TopDesc = nil,
    _stc_LeftBg = nil,
    _stc_LeftImage = nil,
    _stc_LeftGenderIcon = nil,
    _stc_LeftSwitftIcon = nil,
    _txt_LeftTier = nil,
    _txt_LeftName = nil,
    _stc_RightBg = nil,
    _stc_RightImage = nil,
    _stc_RightGenderIcon = nil,
    _stc_RightSwitftIcon = nil,
    _txt_RightTier = nil,
    _txt_RightName = nil,
    _stc_ExchangeDeco = nil,
    _rdo_Inven = nil,
    _txt_InvenMoney = nil,
    _rdo_Ware = nil,
    _txt_WareMoney = nil,
    _btn_Exchange_PC = nil,
    _btn_Cancel_PC = nil,
    _stc_ExchangeBg = nil,
    _txt_ExchangeMoneyTitle = nil,
    _txt_ExchangeMoneyValue = nil,
    _list2_Servant = nil,
    _list2_Content = nil,
    _list2_Btn_List = nil,
    _list2_Image = nil,
    _list2_GenderIcon = nil,
    _list2_ServantName = nil,
    _list2_Tier = nil,
    _list2_SwiftHorse = nil,
    _list2_Verti_Scroll = nil,
    _list2_Verti_Scroll_Up = nil,
    _list2_Verti_Scroll_Down = nil,
    _list2_Verti_Scroll_Ctrl = nil,
    _list2_Hori_Scroll = nil,
    _list2_Hori_Scroll_Up = nil,
    _list2_Hori_Scroll_Down = nil,
    _list2_Hori_Scroll_Ctrl = nil,
    _list2_Txt_NoHorse = nil,
    _edit_Naming = nil,
    _stc_KeyGuide_X = nil,
    _stc_Bottom_KeyGuide = nil,
    _stc_KeyGuide_Y = nil,
    _stc_KeyGuide_A = nil,
    _stc_KeyGuide_B = nil
  },
  _isContentsStallionEnable = ToClient_IsContentsGroupOpen("243"),
  _servantDataTable = {},
  _currentRegionName = nil,
  _servantNo_Left = nil,
  _servantNo_Right = nil,
  _isConsole = false,
  _initailize = false
}
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantExchange_All_1.lua")
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantExchange_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_ServantExchange_All_Init")
function FromClient_ServantExchange_All_Init()
  PaGlobal_ServantExchange_All:initialize()
end
