PaGlobal_ServantMarket_Rental_Mating_All = {
  _ui = {
    _stc_TitleBg = nil,
    _txt_Title = nil,
    _btn_Question_PC = nil,
    _btn_Close_PC = nil,
    _stc_TabGroup = nil,
    _rdo_Tab_Left = nil,
    _rdo_Tab_Center = nil,
    _rdo_Tab_Right = nil,
    _stc_SelectedLine = nil,
    _stc_KeyGuide_LT = nil,
    _stc_KeyGuide_RT = nil,
    _stc_PageBg = nil,
    _txt_PageValue = nil,
    _btn_PageLeft_PC = nil,
    _btn_PageRight_PC = nil,
    _stc_PageLeft_Console = nil,
    _stc_PageRight_Console = nil,
    _btn_Reload_PC = nil,
    _stc_DescIcon = nil,
    _stc_InvenMoneyBG = nil,
    _stc_WarehouseMoneyBG = nil,
    _txt_InvenTitle = nil,
    _txt_Inven = nil,
    _txt_WareTitle = nil,
    _txt_Ware = nil,
    _stc_SkillTooltip = nil,
    _btn_SkillTooltip_Close_PC = nil,
    _stc_SkillTooltip_KeyGuide_B = nil,
    _stc_Bottom_KeyGuides = nil,
    _stc_KeyGuide_A = nil,
    _stc_KeyGuide_B = nil,
    _stc_KeyGuide_X = nil,
    _stc_KeyGuide_RS = nil,
    _stc_KeyGuide_Y = nil,
    _stc_KeyGuide_Y_Tooltip = nil,
    _servantSlot = {},
    _tabButtonList = {},
    _keyguides = {}
  },
  _ENUM_TAB_LEFT = 0,
  _ENUM_TAB_CENTER = 1,
  _ENUM_TAB_RIGHT = 2,
  _STRING_FORCERETURN = PAGetString(Defines.StringSheet_RESOURCE, "PANEL_WINDOW_STABLE_PROMOTEAUTH_FORCEDRETURN"),
  _STRING_RECIEVE_RENTALMONEY = PAGetString(Defines.StringSheet_RESOURCE, "PANEL_SERVANTRENT_RECIEVEMONEYBUTTON"),
  _STRING_RECIEVE_SERVANT = PAGetString(Defines.StringSheet_RESOURCE, "PANEL_WINDOW_PROMOTEMARKET_BUTTON1"),
  _STRING_RECIEVE_CANCEL = PAGetString(Defines.StringSheet_RESOURCE, "PANEL_COMMON_CANCEL"),
  _STRING_REQUEST_MATING = PAGetString(Defines.StringSheet_RESOURCE, "PANEL_STABLE_MARKET_REQUEST"),
  _isContentsStallionEnable = ToClient_IsContentsGroupOpen("243"),
  _isContentsNineTierEnable = ToClient_IsContentsGroupOpen("80"),
  _isContentsEightTierEnable = ToClient_IsContentsGroupOpen("29"),
  _selectSlotNo = nil,
  _selectPage = 0,
  _selectMaxPage = 0,
  _currentTabIdx = nil,
  _auctionInfo = nil,
  _isMatingMarket = nil,
  _MAXSLOTCOUNT = 4,
  _selectIndex = 0,
  _isConsole = false,
  _initailize = false
}
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantMarket_Rental_Mating_All_1.lua")
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantMarket_Rental_Mating_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_ServantMarket_Rental_Mating_All_Init")
function FromClient_ServantMarket_Rental_Mating_All_Init()
  PaGlobal_ServantMarket_Rental_Mating_All:initialize()
end
