PaGlobal_ServantSkillManagement_All = {
  _eType = {learn = 0, notLearn = 1},
  _ui = {
    _stc_TitleBg = nil,
    _txt_TitleIcon = nil,
    _btn_Close = nil,
    _btn_Question = nil,
    _stc_TabGroup = nil,
    _rdo_LearnedSkill = nil,
    _rdo_WishSkill = nil,
    _stc_Line = nil,
    _stc_SelectedLine = nil,
    _stc_KeyGuides_LB = nil,
    _stc_KeyGuides_RB = nil,
    _stc_LearnSkillBg = nil,
    _list2_LearnSkill = nil,
    _list2_LearnSkill_Content = nil,
    _list2_LearnSkill_stc_SkillSlotBg = nil,
    _list2_LearnSkill_stc_SkillExpBg = nil,
    _list2_LearnSkill_circularProg2_SkillExp = nil,
    _list2_LearnSkill_stc_SkillIcon = nil,
    _list2_LearnSkill_txt_SkillExpPercent = nil,
    _list2_LearnSkill_txt_SkillName = nil,
    _list2_LearnSkill_txt_SkillCommand = nil,
    _list2_LearnSkill_btn_Train_PC = nil,
    _list2_LearnSkill_btn_Delete_PC = nil,
    _btn_TrainAll_PC = nil,
    _stc_Center_WishSKillBg = nil,
    _stc_Center_ContentBg = nil,
    _txt_Center_PercentTitle = nil,
    _txt_Center_PercentValue = nil,
    _txt_Center_DeleteSkillTitle = nil,
    _stc_Center_DeleteSkilBg = nil,
    _stc_Delete_PlusIcon = nil,
    _stc_Delete_SkillExpBg = nil,
    _stc_Delete_CircularProg2_SkillExp = nil,
    _stc_Delete_SkillIcon = nil,
    _stc_Delete_SkillExpPercent = nil,
    _stc_Delete_SkillName = nil,
    _stc_Delete_SkillCommand = nil,
    _txt_WishSkillTitle = nil,
    _stc_WishSKillBg = nil,
    _stc_PlusIcon = nil,
    _stc_WishSkill_SkillExpBg = nil,
    _stc_WishSkill_CircularProg2_Exp = nil,
    _stc_WishSkill_SkillIcon = nil,
    _stc_WishSkill_SkillExpPercent = nil,
    _stc_WishSkill_SkillName = nil,
    _stc_WishSkill_SkillCommand = nil,
    _stc_DescBg = nil,
    _txt_Desc = nil,
    _btn_Change_PC = nil,
    _stc_SkillListBg = nil,
    _list2_ServantSkill = nil,
    _list2_ServantSkill_Content = nil,
    _list2_ServantSkill_SkillSlotBG = nil,
    _list2_ServantSkill_SkillExpBg = nil,
    _list2_ServantSkill_CircurlarProg2Exp = nil,
    _list2_ServantSkill_SkillIcon = nil,
    _list2_ServantSkill_SkillExpPercent = nil,
    _list2_ServantSkill_SkillName = nil,
    _list2_ServantSkill_SkillCommand = nil,
    _stc_BottomBg_Console = nil,
    _stc_KeyGuide_A = nil,
    _stc_KeyGuide_B = nil,
    _stc_KeyGuide_Y = nil,
    _keyguides = {}
  },
  _rdoTab = {},
  _currentWishSkillIdx = nil,
  _currentChangeSkillIdx = nil,
  _isCheckWishSkill = false,
  _currentServantNo = nil,
  _currentServantInfo = nil,
  _deleteSkillName = nil,
  _isClickedWishSkill = false,
  _initialize = false,
  _isConsole = false,
  _ori_PanelY = 0,
  _ori_DescY = 0,
  _ori_WishBgY = 0,
  _tabType = 0,
  _isContentsTrainingEnable = ToClient_IsContentsGroupOpen("60"),
  _isContentsTrainingAllEnable = ToClient_IsContentsGroupOpen("452"),
  _isContentsStallionEnable = ToClient_IsContentsGroupOpen("243")
}
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantSkillManagement_All_1.lua")
runLua("UI_Data/Script/Window/Servant/NewUI/Panel_Dialog_ServantSkillManagement_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_ServantSkillManagement_All_Init")
function FromClient_ServantSkillManagement_All_Init()
  PaGlobal_ServantSkillManagement_All:initialize()
end
