PaGlobal_GuildInfo_All = {
  _ui = {
    stc_LeftBg = nil,
    stc_TopBg = nil,
    stc_MarkBg = nil,
    stc_Mark = nil,
    stc_MarkOutLine = nil,
    txt_Name = nil,
    txt_MasterName = nil,
    btn_InfoWeb = nil,
    btn_MarkChange = nil,
    txt_Grade = nil,
    btn_GradeUp = nil,
    txt_ProtectedCount = nil,
    btn_IncreaseProtectedCount = nil,
    txt_GuildPoint = nil,
    txt_OwnedArea = nil,
    txt_Vehicle = nil,
    txt_Money = nil,
    btn_WareHouse = nil,
    btn_Arsha = nil,
    btn_GetMaster = nil,
    btn_Recruit = nil,
    btn_Introduce = nil,
    btn_Vaction = nil,
    btn_VactionReturn = nil,
    btn_Dismiss = nil,
    btn_TaxPayment = nil,
    stc_LeftBottomBg = nil,
    stc_Notice_Title = nil,
    edit_Notice = nil,
    btn_SaveNotice = nil,
    stc_KeyGuide_X = nil,
    stc_QuestionWar = nil,
    stc_RightBg = nil,
    rdo_Decleared = nil,
    rdo_Recieved = nil,
    stc_SelectLine = nil,
    stc_KeyGuide_LT = nil,
    stc_KeyGuide_RT = nil,
    stc_WarGuildList = nil,
    list2_WarInfo = nil,
    list2_Recieved = nil,
    stc_TodayCommentBg = nil,
    stc_webControl = nil,
    stc_WarHpSet = nil,
    stc_ConsoleOnly = nil,
    stc_GuildMark_Console = nil,
    stc_ConsoleMark = nil,
    stc_ConsoleBg = nil,
    _guildlistTable = {}
  },
  _contentsOption = {
    isGuildBattle = false,
    isProtectGuildMember = false,
    isContentsGuildDuel = false,
    isContentsGuildInfo = false,
    isContentsArsha = false,
    isContentsGuildHouse = false,
    isCanDoReservation = false,
    isPopUpContentsEnable = false
  },
  _targetGuildNo = nil,
  _targetGuildName = nil,
  _targetUserNo = nil,
  _currentTabIdx = 0,
  _selfPlayer = nil,
  _isVacation = nil,
  _urlCache = "",
  _guildCommentsWebUrl = nil,
  _initialize = false,
  _isConsole = false,
  _isKR2 = false
}
runLua("UI_Data/Script/Window/Guild/NewUI/Panel_GuildInfo_All_1.lua")
runLua("UI_Data/Script/Window/Guild/NewUI/Panel_GuildInfo_All_2.lua")
runLua("UI_Data/Script/Window/Guild/NewUI/Panel_GuildInfo_All_3.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_GuildInfo_All_Init")
function FromClient_GuildInfo_All_Init()
  PaGlobal_GuildInfo_All:initialize()
end
