PaGlobal_GuildMain_All = {
  _ui = {
    stc_Title = nil,
    txt_Title = nil,
    btn_Close = nil,
    btn_Question = nil,
    btn_Refresh = nil,
    btn_PearlApp = nil,
    btn_PopUp = nil,
    stc_TabBG = nil,
    stc_RdoBtnBg = nil,
    rdo_BasicInfo = nil,
    rdo_MemberList = nil,
    rdo_Quest = nil,
    rdo_Skill = nil,
    rdo_Warfare = nil,
    rdo_History = nil,
    rdo_Recruit = nil,
    rdo_GuildBattle = nil,
    rdo_ManuFacture = nil,
    rdo_Alliance = nil,
    rdo_AllianceList = nil,
    rdo_Marcenary = nil,
    rdo_BossSummon = nil,
    stc_KeyGuid_LB = nil,
    stc_KeyGuid_RB = nil,
    stc_SelectBar = nil,
    stc_BasicInfo_Bg = nil,
    stc_MemberList_Bg = nil,
    stc_Quest_Bg = nil,
    stc_Skill_Bg = nil,
    stc_Warfare_Bg = nil,
    stc_History_Bg = nil,
    stc_Recruit_Bg = nil,
    stc_GuildBattle_Bg = nil,
    stc_ManuFacture_Bg = nil,
    stc_Alliance_Bg = nil,
    stc_AllianceList_Bg = nil,
    stc_Mercenary_Bg = nil,
    stc_BossSummon_Bg = nil,
    stc_AllianceInvite_Bg = nil,
    stc_keyGuide_LB = nil,
    stc_keyGuide_RB = nil,
    stc_Keyguide_Bg = nil,
    stc_Keyguide_A = nil,
    stc_Keyguide_B = nil,
    stc_Keyguide_X = nil,
    stc_Keyguide_Y = nil,
    stc_Keyguide_LT = nil,
    stc_Keyguide_VertiDpad = nil,
    stc_Keyguide_HoriDpad = nil,
    stc_Keyguide_RS = nil,
    stc_Keyguide_LC = nil,
    stc_Keyguide_RC = nil,
    rdo_btnTable = {}
  },
  _tabData = {},
  _tabBtnCount = 13,
  _tabBtnConsole = {},
  _keyGuideTable = {},
  _eTABINDEX = {
    _BASIC = 0,
    _MEMBERLIST = 1,
    _QUSET = 2,
    _SKILL = 3,
    _WARFARE = 4,
    _HISTORY = 5,
    _RECRUIT = 6,
    _GUILDBATTLE = 7,
    _MANUFACTURE = 8,
    _ALLIANCE = 9,
    _ALLIANCELIST = 10,
    _MARCENARY = 11,
    _BOSSSUMMON = 12,
    _COUNT = 13
  },
  _tooltip = {
    [0] = "LUA_GUILD_GUILDINFO_TITLE",
    "LUA_GUILD_TEXT_GUILDLIST",
    "LUA_GUILD_TEXT_GUILDQUEST",
    "LUA_GUILD_TEXT_GUILDSKILL",
    "LUA_GUILD_TEXT_GUILDWARFAREINFO",
    "LUA_GUILD_TEXT_GUILDHISTORY",
    "LUA_GUILD_RECRUITMENTGUILD",
    "LUA_MENU_GUILDBATTLE",
    "LUA_GUILD_TEXT_GUILDMANUFACTURE",
    "LUA_GUILDALLIANCE_TITLE",
    "LUA_GUILD_TAB_ALLIANCELISTITLE",
    "LUA_PANEL_GUILD_VOLUNTEER_LIST_TAB_BUTTON_TOOLTIP",
    "LUA_NEW_GUILDRAID_SUMMON"
  },
  _alignedKeyguide = {},
  _originSizeY = 0,
  _currentTabIdx = nil,
  _currentTabIdxConsole = nil,
  _initialize = false,
  _isConsole = false
}
runLua("UI_Data/Script/Window/Guild/NewUI/Panel_GuildMain_All_1.lua")
runLua("UI_Data/Script/Window/Guild/NewUI/Panel_GuildMain_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_GuildMain_All_Init")
function FromClient_GuildMain_All_Init()
  PaGlobal_GuildMain_All:initialize()
end
