PaGlobal_UIModify = {
  _eBtnType = {
    preset1 = 0,
    preset2 = 1,
    preset3 = 2,
    battleMode = 3,
    revertMode = 4
  },
  _panelID = {
    ExpGage = 1,
    ServantIcon = 2,
    Radar = 3,
    Quest = 4,
    Chat0 = 5,
    Chat1 = 6,
    Chat2 = 7,
    Chat3 = 8,
    Chat4 = 9,
    GameTip = 10,
    QuickSlot = 11,
    HPBar = 12,
    Pvp = 13,
    ClassResource = 14,
    Adrenallin = 15,
    UIMain = 16,
    House = 17,
    NewEquip = 18,
    Party = 19,
    TimeBar = 20,
    ActionGuide = 21,
    KeyGuide = 22,
    NewQuickSlot0 = 23,
    NewQuickSlot1 = 24,
    NewQuickSlot2 = 25,
    NewQuickSlot3 = 26,
    NewQuickSlot4 = 27,
    NewQuickSlot5 = 28,
    NewQuickSlot6 = 29,
    NewQuickSlot7 = 30,
    NewQuickSlot8 = 31,
    NewQuickSlot9 = 32,
    NewQuickSlot10 = 33,
    NewQuickSlot11 = 34,
    NewQuickSlot12 = 35,
    NewQuickSlot13 = 36,
    NewQuickSlot14 = 37,
    NewQuickSlot15 = 38,
    NewQuickSlot16 = 39,
    NewQuickSlot17 = 40,
    NewQuickSlot18 = 41,
    NewQuickSlot19 = 42,
    SkillCoolTime = 43,
    MainQuest = 44,
    LargeParty = 45,
    SkillCoolTimeQuickSlot0 = 46,
    SkillCoolTimeQuickSlot1 = 47,
    SkillCoolTimeQuickSlot2 = 48,
    SkillCoolTimeQuickSlot3 = 49,
    SkillCoolTimeQuickSlot4 = 50,
    SkillCoolTimeQuickSlot5 = 51,
    SkillCoolTimeQuickSlot6 = 52,
    SkillCoolTimeQuickSlot7 = 53,
    SkillCoolTimeQuickSlot8 = 54,
    SkillCoolTimeQuickSlot9 = 55,
    MainStatusRemaster = 56,
    ServantIconRemaster = 57,
    AppliedBuffList = 58,
    LeftIcon = 59,
    RightIcon = 60,
    AreaOfHadum = 61,
    Stamina = 62,
    killLog = 63
  },
  _panelControl = {},
  _panelCount = 0,
  _panelPool = {},
  _panelPoolBG = nil,
  _swapPanelList = {},
  _ui = {
    panelBG = nil,
    titleBG = nil,
    chk_Collapse = nil,
    btn_win_close = nil,
    balckBG = nil,
    grid_BG = nil,
    main_BG = nil,
    btn_UIFreeSet1 = nil,
    btn_UIFreeSet2 = nil,
    btn_UIFreeSet3 = nil,
    btn_CleanMode = nil,
    btn_RevertMod = nil,
    sub_BG = nil,
    txt_UISize = nil,
    txt_UI_LOW = nil,
    txt_UI_HIGH = nil,
    slider_UI_Scale = nil,
    btn_Scale = nil,
    chk_remsaterUI = nil,
    chk_FieldView = nil,
    chk_QuickSlotMagnetic = nil,
    chk_GridView = nil,
    desc_BG = nil,
    txt_Desc = nil,
    btn_save = nil,
    btn_reset = nil
  },
  _uiSave = {
    txt_Desc = nil,
    btn_SaveClose = nil,
    btn_SaveDefault = nil,
    btn_SaveUI1 = nil,
    btn_SaveUI3 = nil,
    btn_SaveUI2 = nil,
    bg_Block = nil
  },
  _BG_Texture = {
    {
      107,
      1,
      159,
      54
    },
    {
      1,
      1,
      53,
      54
    },
    {
      53,
      1,
      106,
      54
    }
  },
  _closePanelState = {
    [0] = false,
    [1] = false,
    [2] = false,
    [3] = false,
    [4] = false
  },
  _closeEmptyPanelState = {
    [0] = false,
    [1] = false,
    [2] = false,
    [3] = false,
    [4] = false
  },
  _chatPanelIsOpenState = {
    [1] = false,
    [2] = false,
    [3] = false,
    [4] = false,
    [5] = false
  },
  _cachePosX = {},
  _cachePosY = {},
  _cacheSizeX = {},
  _cacheSizeY = {},
  _cachePreScale = {},
  _preScale = 0,
  _currentScale = 100,
  _minScale = 50,
  _maxScale = 120,
  _replaceScale = 0,
  _nowCurrentPercent = 0,
  _saveScale = 100,
  _renderMode = nil,
  _isMenu = true,
  _prevRemasterUI = nil,
  _isShowRemasterUI = true,
  _beforeUiMode = Defines.UIMode.eUIMode_Default,
  _initialize = false,
  _original_MouseX = 0,
  _original_MouseY = 0,
  _original_controlPosX = 0,
  _original_controlPosY = 0,
  _posGapX = 0,
  _posGapY = 0
}
runLua("UI_Data/Script/Window/UI_Setting/Panel_Window_UIModify_All_1.lua")
runLua("UI_Data/Script/Window/UI_Setting/Panel_Window_UIModify_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_UISettingInit")
function FromClient_UISettingInit()
  PaGlobal_UIModify:initialize()
end
