PaGlobal_DeadMessage_All = {
  _ui = {
    stc_centerBG = nil,
    txt_deathTitle = nil,
    txt_resurrectionTime = nil,
    txt_GuildSkillApply = nil,
    stc_lostItemBG = nil,
    stc_lineTop = nil,
    stc_lineBottom = nil,
    list2_lostItem = nil,
    list2_content = nil,
    stc_resurrectionBG = nil,
    btn_largeTemplate = nil,
    btn_smallTemplate = nil,
    _button_Respawn = {},
    btn_noticeIcon = nil,
    btn_selectButton_console = nil,
    btn_useItemCheck = nil,
    btn_useFairyCheck = nil,
    txt_siegeNotice = nil,
    stc_paneltyBG = nil
  },
  _eButtonType = {
    GuildObServerMode = 1,
    Observer = 2,
    SavageDefence = 3,
    NationSiege_BlackSpirit = 4,
    Immediate = 5,
    InSiegeingFortress = 6,
    LocalWar = 7,
    Plunder = 8,
    GuildBatle = 9,
    GuildTeamBattle = 10,
    OutsideGate = 11,
    InsideGate = 12,
    ByOtherPlayer = 13,
    Exploration = 14,
    NearTown = 15,
    Volunteer = 16,
    AdvancedBase = 17,
    GuildSpawn = 18,
    Competition = 19,
    TimeOver = 20,
    count = 21
  },
  _eRespawnType = {
    respawnType_None = 0,
    respawnType_Immediate = 1,
    respawnType_ByOtherPlayer = 2,
    respawnType_Exploration = 3,
    respawnType_NearTown = 4,
    respawnType_TimeOver = 5,
    respawnType_InSiegeingFortress = 6,
    respawnType_LocalWar = 7,
    respawnType_AdvancedBase = 8,
    respawnType_GuildSpawn = 9,
    respawnType_Competition = 10,
    respawnType_SavageDefence = 11,
    respawnType_Volunteer = 12,
    respawnType_GuildBatle = 13,
    respawnType_Plunder = 14,
    respawnType_GuildTeamBattle = 15,
    respawnType_OutsideGate = 16,
    respawnType_InsideGate = 17,
    respawnType_NationSiege_BlackSpirit = 19,
    respawnType_Count = 20
  },
  _eDeadType = {
    Dead_Normal = 0,
    DeadLocate_InPlunder = 1,
    DeadLocate_InBattleGround = 2,
    DeadLocate_InCompetition = 3,
    DeadLocate_InSavageDefence = 4,
    DeadLocate_InGuildBattle = 5,
    DeadLocate_InGuildTeamBattle = 6,
    DeadLocate_InPVP = 7,
    DeadLocate_InLocarWar = 8,
    DeadLocate_InPrision = 9,
    DeadLocate_InSiegeBeingChannel = 10,
    DeadLocate_InSiegeBeingInCurrentPos = 11,
    DeadLocate_InSiegeBattle = 12,
    DeadLocate_InMajorSiegeBattle = 13,
    DeadLocate_InNoAccessArea = 14,
    DeadLocate_InArena = 15,
    IsSpecialCharacter = 16,
    DeadLocate_InNationSiege = 17,
    DeadLocate_InBloodAltar = 18
  },
  _aniType = {_changeColor = 0, _changeScale = 1},
  _paneltyColor = {RED = 0, BLUE = 1},
  _ButtonString = {},
  _ButtonEvent = {},
  _resurrectionTime = 600,
  _lastUpdateTime = 0,
  _revivalTime = 600,
  _buttonAbleTime = 10,
  _buttonWaitTime = 0,
  _isButtonWaitTimeEnd = false,
  _isUseButtonAbleTime = false,
  _isObserverMode = false,
  _tempButtonAbleTimeForGuildObserver = nil,
  _startTimeForGuildObserver = nil,
  _isHasResotreExp = false,
  _isAblePvPMatchRevive = false,
  _currentDeadType = nil,
  _paneltyStringMaxCount = 10,
  _currentPaneltyStringCount = 0,
  _PaneltyColor = {},
  _PaneltyString = {},
  _isSkipDeathPenalty = false,
  _respawnButtonMaxCount = 9,
  _ButtonListByDeadType = {},
  _buttonTypeArray = nil,
  _deadCheckTime = 0,
  _deadCheckGap = 1,
  _useItem = false,
  _useFairy = false,
  _attackerActorKeyRaw = nil,
  _isConsole = false,
  _initialize = false
}
runLua("UI_Data/Script/Window/DeadMessage/Panel_Window_DeadMessage_All_1.lua")
runLua("UI_Data/Script/Window/DeadMessage/Panel_Window_DeadMessage_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_DeadMessage_All_Init")
function FromClient_DeadMessage_All_Init()
  PaGlobal_DeadMessage_All:initialize()
end
