PaGlobal_LifeRanking_All = {
  _ui = {
    stc_TitleBG = nil,
    btn_Close = nil,
    btn_Question = nil,
    stc_RankingTypeBG = nil,
    stc_KeyGuideLB = nil,
    stc_KeyGuideRB = nil,
    stc_RankingIcons = {},
    txt_CurRankingTypeTitle = nil,
    stc_LeftBG = nil,
    stc_GradeBG = nil,
    stc_CurRankingIconBG = nil,
    txt_CurRankingGradeValue = nil,
    txt_CurRankingType = nil,
    stc_GradeBar = nil,
    stc_GradeBarArrow = nil,
    txt_CurRankingDesc = nil,
    stc_MyRanking = nil,
    txt_MyRanking_Title = {},
    txt_MyRanking_Value = {},
    stc_ListTitleBG = nil,
    txt_CharacterNameTitle = nil,
    txt_GuildNameTitle = nil,
    txt_RankTitle = nil,
    list2_Ranking = nil,
    txt_Comment = nil,
    stc_BottomBG = nil,
    txt_KeyGuide_A = nil,
    txt_KeyGuide_B = nil,
    tooltipBG = nil,
    tooltipName = nil,
    tooltipDesc = nil
  },
  _MAX_RANKTYPE_COUNT = 20,
  _eType = {
    _GATHER = 0,
    _FISHING = 1,
    _HUNTING = 2,
    _COOKING = 3,
    _ALCHEMY = 4,
    _MANUFACTURE = 5,
    _HORSE = 6,
    _TRADE = 7,
    _GROWTH = 8,
    _SAIL = 9,
    _TEMP1 = 10,
    _BARTER = 11,
    _TEMP2 = 12,
    _TEMP3 = 13,
    _TEMP4 = 14,
    _TEMP5 = 15,
    _WEALTH = 16,
    _COMBAT = 17,
    _LOCALWAR = 18,
    _PVP = 19
  },
  _tabName = {
    [0] = PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_GATHER"),
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_FISH"),
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_HUNT"),
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_COOK"),
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_ALCHEMY"),
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_MANUFACTURE"),
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_HORSE"),
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_TRADE"),
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_GROWTH"),
    PAGetString(Defines.StringSheet_GAME, "LUA_PARTYCOMBAT_TAB_SAIL"),
    "-",
    PAGetString(Defines.StringSheet_GAME, "LUA_SELFCHARACTERINFO_BARTER"),
    "-",
    "-",
    "-",
    "-",
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_WEALTH"),
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_COMBAT"),
    PAGetString(Defines.StringSheet_GAME, "LUA_LIFERANKING_TAB_LOCALWAR"),
    PAGetString(Defines.StringSheet_GAME, "LUA_PARTYCOMBAT_NAK_PVPMATCH_NAME")
  },
  _rankTypeName = {
    [0] = "GATHERING",
    "FISHING",
    "HUNT",
    "COOK",
    "ALCHEMY",
    "CRAFTING",
    "TRAINING",
    "TRADE",
    "FARMING",
    "SAILING",
    "",
    "BARTER",
    "",
    "",
    "",
    "",
    "WEALTH",
    "GROWTH",
    "REDWAR",
    ""
  },
  _rankContentsOption = {
    [0] = true,
    [1] = true,
    [2] = ToClient_IsContentsGroupOpen("28"),
    [3] = true,
    [4] = true,
    [5] = true,
    [6] = true,
    [7] = true,
    [8] = true,
    [9] = _ContentsGroup_Sail,
    [10] = false,
    [11] = _ContentsGroup_Barter,
    [12] = false,
    [13] = false,
    [14] = false,
    [15] = false,
    [16] = true,
    [17] = true,
    [18] = ToClient_IsContentsGroupOpen("43"),
    [19] = true
  },
  _listUpdate = {
    [0] = false,
    [1] = false,
    [2] = false,
    [3] = false,
    [4] = false,
    [5] = false,
    [6] = false,
    [7] = false,
    [8] = false,
    [9] = false,
    [10] = false,
    [11] = false,
    [12] = false,
    [13] = false,
    [14] = false,
    [15] = false,
    [16] = false,
    [17] = false,
    [18] = false,
    [19] = false
  },
  _rankIconTextureUV = {
    [0] = {
      _x1 = 130,
      _y1 = 1,
      _x2 = 165,
      _y2 = 31
    },
    [1] = {
      _x1 = 130,
      _y1 = 32,
      _x2 = 165,
      _y2 = 62
    },
    [2] = {
      _x1 = 130,
      _y1 = 63,
      _x2 = 165,
      _y2 = 93
    }
  },
  _keyGuideGroup = {},
  _rankerData = {},
  _selectedTabIdx = 0,
  _listCount = nil,
  _defaultTooltipSizeX = 0,
  _initialize = false,
  _serverChange = true,
  _isFamilyNameShow = true,
  _gradeFontColor = {
    A = Defines.Color.C_FFD05D48,
    B = Defines.Color.C_FFF5BA3A,
    C = Defines.Color.C_FF83A543,
    D = Defines.Color.C_FF4898D0,
    E = Defines.Color.C_FFB9C2DC
  },
  _rankFontColor = {
    [0] = Defines.Color.C_FFFFDD00,
    [1] = Defines.Color.C_FFD7E6F4,
    [2] = Defines.Color.C_FFF5BA3A
  },
  _lifeGradeString = {},
  _defaultFontColor = Defines.Color.C_FFDDC39E,
  _rightShowRankType = 0,
  _currentTooltipIndex = nil,
  _isConsole = false,
  _isPadSnap = false
}
runLua("UI_Data/Script/Window/LifeRanking/Panel_LifeRanking_All_1.lua")
runLua("UI_Data/Script/Window/LifeRanking/Panel_LifeRanking_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_LifeRanking_All_Init")
function FromClient_LifeRanking_All_Init()
  PaGlobal_LifeRanking_All:initialize()
end
