PaGlobal_ChannelSelect_All = {
  _ui = {
    btn_Close = nil,
    btn_Qusetion = nil,
    stc_subFrame = nil,
    stc_AllBG = nil,
    stc_blockBG = nil,
    stc_descBg = nil,
    stc_decoBg = nil,
    stc_Icon_War = nil,
    stc_Icon_NoEnterance = nil,
    stc_Icon_Maintenance = nil,
    stc_Icon_PrepareToStop = nil,
    stc_Icon_ExpEvent = nil,
    stc_Icon_Premium = nil,
    stc_Icon_PK = nil,
    stc_Icon_CrossPlay = nil,
    txt_Icon_Time = nil,
    txt_Status = nil,
    chk_ShowDesc = nil,
    rdo_Templeate = nil,
    stc_DescPanel = nil,
    txt_ChannelSelectTitle = nil,
    txt_ChannelSelectDesc = nil,
    txt_SpeedTitle = nil,
    txt_SpeedDesc = nil,
    txt_SeasonTitle = nil,
    txt_SeasonDesc = nil,
    txt_PkTitle = nil,
    txt_PkDesc = nil,
    txt_SiegeTitle = nil,
    txt_SiegeBalenos = nil,
    txt_SiegeSerendia = nil,
    txt_SiegeCalpheon = nil,
    txt_SiegeMedia = nil,
    txt_SiegeValencia = nil,
    txt_Schedule = nil,
    txt_Schedule_Siege = nil,
    txt_Schedule_NodeWar = nil,
    stc_KeyguideBg = nil,
    stc_KeyGuide_A = nil,
    stc_KeyGuide_B = nil,
    txt_Icon_SeasonCoolTime = nil
  },
  _string_BusyState = {
    [0] = PAGetString(Defines.StringSheet_GAME, "LUA_SERVERSELECT_BUSYSTATE_0"),
    "",
    PAGetString(Defines.StringSheet_GAME, "LUA_SERVERSELECT_BUSYSTATE_2"),
    PAGetString(Defines.StringSheet_GAME, "LUA_SERVERSELECT_BUSYSTATE_3"),
    PAGetString(Defines.StringSheet_GAME, "LUA_SERVERSELECT_BUSYSTATE_4")
  },
  _string_WarName = {
    [-2] = "\235\170\168\235\145\144 \235\182\136\234\176\128",
    [-1] = "\235\170\168\235\145\144 \234\176\128\235\138\165",
    [0] = "\235\176\156\235\160\136\235\133\184\236\138\164",
    [1] = "\236\132\184\235\160\140\235\148\148\236\149\132",
    [2] = "\236\185\188\237\142\152\236\152\168",
    [3] = "\235\169\148\235\148\148\236\149\132",
    [4] = "\235\176\156\235\160\140\236\139\156\236\149\132"
  },
  _string_IconTooltip = {
    [1] = PAGetString(Defines.StringSheet_GAME, "LUA_CHANNELSELECTE_WARICON"),
    [2] = PAGetString(Defines.StringSheet_GAME, "LUA_CHANNELSELECTE_NOENTERANCEICON"),
    [3] = PAGetString(Defines.StringSheet_GAME, "LUA_CHANNELSELECT_SEASONCOOLTIME"),
    [4] = PAGetString(Defines.StringSheet_GAME, "LUA_CHANNELSELECT_NORMALCOOLTIME"),
    [5] = PAGetString(Defines.StringSheet_GAME, "LUA_CHANNELSELECTE_MAINTENANCEICON"),
    [6] = PAGetString(Defines.StringSheet_GAME, "LUA_CHANNELSELECTE_EXPEVENTICON"),
    [7] = PAGetString(Defines.StringSheet_GAME, "LUA_GAMEEXIT_SEVERSELECT_PCROOMSERVER"),
    [8] = PAGetString(Defines.StringSheet_GAME, "LUA_PREPARE_TO_STOP_SERVER"),
    [9] = PAGetString(Defines.StringSheet_RESOURCE, "PANEL_SERVERSELECT_CROSSPLAY_ICONGUIDE"),
    [10] = PAGetString(Defines.StringSheet_GAME, "LUA_SEASONCONTENT_SEASONSERVER"),
    [11] = PAGetString(Defines.StringSheet_GAME, "LUA_GAMEEXIT_SEVERSELECT_PK"),
    [12] = PAGetString(Defines.StringSheet_GAME, "LUA_SERVERSELECT_INVITEFRIENDSSERVER"),
    [13] = PAGetString(Defines.StringSheet_GAME, "LUA_SERVERSELECT_EXPEVENT")
  },
  _descTable = {},
  _serverIndexTable = {},
  _groupBg = {},
  _channelSelectUIPool = {},
  _selectChannel = {},
  _channeUIMaxCount = 0,
  _serverCountInGroup = 0,
  _channelGroupCount = {},
  _bgCount = 0,
  _elapsedTime = 0,
  _friendInviteServerIdx = nil,
  _friendInviteWorldIdx = nil,
  _content_IsCalpheonOpen = ToClient_IsContentsGroupOpen("2"),
  _content_IsMediaOpen = ToClient_IsContentsGroupOpen("3"),
  _content_IsValenciaOpen = ToClient_IsContentsGroupOpen("4"),
  _content_IsSiegeEnable = ToClient_IsContentsGroupOpen("21"),
  _useFrameDesc = true,
  _serverDescControls = {},
  _descButtonCount = 0,
  _descButtonSizeY = 0,
  _descSpanSize = 0,
  _minDescBGSizeY = 10,
  _descBGSizeX = 0,
  _showDescAniSpeed = 500,
  _hideDescAniSpeed = 2000,
  _isChannelCountLow = false,
  _isConsole = false,
  _isAppliedSeasonTexture = false,
  _initialize = false
}
runLua("UI_Data/Script/Window/GameExit/Panel_ChannelSelect_All_1.lua")
runLua("UI_Data/Script/Window/GameExit/Panel_ChannelSelect_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_ChannelSelect_All_Init")
function FromClient_ChannelSelect_All_Init()
  PaGlobal_ChannelSelect_All:initialize()
end
