_ContentsOption_CH_GameType = isGameTypeKR2()
_ContentsOption_CH_OptionUseAlchemyStone = ToClient_IsContentsGroupOpen("35")
_ContentsOption_CH_WepHelperControl = _ContentsOption_CH_GameType
_ContentsOption_CH_LoadingImage = _ContentsOption_CH_GameType
