PaGlobal_Command_All = {
  _ui = {
    _stc_commandEffectBg = nil,
    _stc_resultPerfect = nil,
    _stc_commandBg = nil,
    _stc_resultBad = nil,
    _txt_command = {},
    _stc_currectEffect0 = nil,
    _stc_timerBg = nil,
    _stc_timerBar = nil,
    _stc_resultSuccess = nil,
    _stc_resultFailed = nil,
    _txt_fishGrade = nil
  },
  _gameOptionActionKey = {
    Forward = 0,
    Back = 1,
    Left = 2,
    Right = 3,
    Attack = 4,
    SubAttack = 5,
    Dash = 6,
    Jump = 7
  },
  _commandStartIndex = 1,
  _commandEndIndex = 10,
  _fishCount = 0,
  _isCommandFinished = false,
  _currentCommandIndex = 0,
  _commands = {},
  _passedTimePerNext = 0,
  _fishCommandCount = {
    [0] = {min = 2, max = 3},
    {min = 4, max = 5},
    {min = 5, max = 6},
    {min = 7, max = 9},
    {min = 10, max = 10}
  },
  _commandColor = {
    [0] = Defines.Color.C_FFFF0000,
    Defines.Color.C_FFD20000,
    Defines.Color.C_FFF26A6A,
    Defines.Color.C_FF775555,
    Defines.Color.C_FFFFD46D,
    Defines.Color.C_FFFFF3AF,
    Defines.Color.C_FFEDE699,
    Defines.Color.C_FFEF9C7F,
    Defines.Color.C_FFEE7001,
    Defines.Color.C_FFFF4729,
    Defines.Color.C_FFFFFFFF,
    Defines.Color.C_FF858585,
    Defines.Color.C_FFDFDFDF,
    Defines.Color.C_FFB5FF6D,
    Defines.Color.C_FFC8FFC8,
    Defines.Color.C_FF6DC6FF,
    Defines.Color.C_FF96D4FC,
    Defines.Color.C_FF00C0D7,
    Defines.Color.C_FFC4BEBE,
    Defines.Color.C_FFFFAB6D,
    Defines.Color.C_FFB75EDD,
    Defines.Color.C_FFFFCE22,
    Defines.Color.C_FFFFEEA0,
    Defines.Color.C_FFFAE696,
    Defines.Color.C_FFF0EF9D,
    Defines.Color.C_FFD8CABA,
    Defines.Color.C_FFEEBA3E,
    Defines.Color.C_FFC1FFC2,
    Defines.Color.C_FFBBFF84,
    Defines.Color.C_FF8484FF,
    Defines.Color.C_FFFF8484,
    Defines.Color.C_FFFFFB84,
    Defines.Color.C_FFFF973A,
    Defines.Color.C_FF84D2FF,
    Defines.Color.C_FF008AFF,
    Defines.Color.C_FF0054FF,
    Defines.Color.C_FF67FFA4,
    Defines.Color.C_FFFF7C67,
    Defines.Color.C_FF76CAFF,
    Defines.Color.C_FFFF5F5F,
    Defines.Color.C_FFFF3BF8,
    Defines.Color.C_FFFFBC3A,
    Defines.Color.C_FFB10000,
    Defines.Color.C_FF7F7F7F,
    Defines.Color.C_FF2478FF,
    Defines.Color.C_FFEFEFEF,
    Defines.Color.C_FFF03838,
    Defines.Color.C_FFEF5378,
    Defines.Color.C_FFFF8957,
    Defines.Color.C_FF3BD3FF,
    Defines.Color.C_FFC4A68A,
    Defines.Color.C_FF748CAB,
    Defines.Color.C_FFA8FC00,
    Defines.Color.C_FFFBFF8A,
    Defines.Color.C_FFFF8A8A,
    Defines.Color.C_FFFF3636,
    Defines.Color.C_FF7800D5,
    Defines.Color.C_FFFFAE00,
    Defines.Color.C_FFD98F00,
    Defines.Color.C_FFD96100,
    Defines.Color.C_FFCE3A00,
    Defines.Color.C_FFC00000,
    Defines.Color.C_FFF4D35D,
    Defines.Color.C_FF5578B4,
    Defines.Color.C_FF00C2EA,
    Defines.Color.C_FF844BE3,
    Defines.Color.C_FFE37F4B,
    Defines.Color.C_FFDA0000,
    Defines.Color.C_FFBCF44B,
    Defines.Color.C_FF4BF4B5,
    Defines.Color.C_FFFF4C4C,
    Defines.Color.C_FFFF874C,
    Defines.Color.C_FFAEFF9B,
    Defines.Color.C_FF9B9BFF,
    Defines.Color.C_FF8737FF,
    Defines.Color.C_FFE7E7E7,
    Defines.Color.C_FFD2B4FF,
    Defines.Color.C_FFFF9BFE,
    Defines.Color.C_FF6B6B6B,
    Defines.Color.C_FF999999,
    Defines.Color.C_FFFFEF82,
    Defines.Color.C_FFFF4B4B,
    Defines.Color.C_FF84FFF5,
    Defines.Color.C_FFAAAAAA,
    Defines.Color.C_FF926CFF,
    Defines.Color.C_FFF601FF,
    Defines.Color.C_FF8EBD00,
    Defines.Color.C_FFFFCF4C,
    Defines.Color.C_FF804040,
    Defines.Color.C_FF40D7FD,
    Defines.Color.C_FFDCD489,
    Defines.Color.C_FFFFDD81,
    Defines.Color.C_FFFFCE57,
    Defines.Color.C_FFF4A72D,
    Defines.Color.C_FFE26A13,
    Defines.Color.C_FFE03A0D,
    Defines.Color.C_FFF68383,
    Defines.Color.C_FFECADAD,
    Defines.Color.C_FFE5C6C6,
    Defines.Color.C_FFCECECE,
    Defines.Color.C_ffff8181,
    Defines.Color.C_ffdeff6d,
    Defines.Color.C_FF387f14,
    Defines.Color.C_FFf570a1,
    Defines.Color.C_FF25c28b,
    Defines.Color.C_FF3E5CFF,
    Defines.Color.C_FFBE4A00,
    Defines.Color.C_FF00A1FF,
    Defines.Color.C_FFA3EF00
  },
  _keyCommandSize = {x = 0, y = 0},
  _padCommandSize = {x = 34, y = 34},
  _commandInterval = {x = 0, y = 0},
  _isConsole = false,
  _initialize = false
}
runLua("UI_Data/Script/Widget/MiniGame/Panel_MiniGame_Command_All_1.lua")
runLua("UI_Data/Script/Widget/MiniGame/Panel_MiniGame_Command_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_Command_All_Init")
function FromClient_Command_All_Init()
  PaGlobal_Command_All:initialize()
end
