PaGlobal_WorkerManager_All = {
  _ui = {
    stc_titleBg = nil,
    txt_title = nil,
    stc_radioBg = nil,
    radio_worker = nil,
    radio_advence = nil,
    stc_selectBar = nil,
    combo_town = nil,
    combo_townlist = nil,
    combo_grade = nil,
    combo_gradelist = nil,
    stc_restoreGroup = nil,
    txt_restoreGuide = nil,
    stc_restoreIconBg = nil,
    stc_restoreIcon = nil,
    slider_Bg = nil,
    slider_btn = nil,
    txt_itemCnt = nil,
    txt_itemVal = nil,
    stc_restoreDesc = nil,
    stc_workerListGroup = nil,
    list2_worker = nil,
    stc_workerAdvenceGroup = nil,
    stc_selectedWorkerSlot = nil,
    list2_advence = nil,
    stc_noticeBox = nil,
    txt_normal = nil,
    txt_nobody = nil,
    txt_result = nil,
    stc_selectedBox = nil,
    stc_border_normal = nil,
    stc_border_green = nil,
    stc_border_blue = nil,
    stc_border_yellow = nil,
    stc_border_orange = nil,
    stc_image = nil,
    stc_expBg = nil,
    progress_exp = nil,
    txt_workCnt = nil,
    txt_workerInfo = nil,
    txt_workerTown = nil,
    stc_advenceBg = nil,
    progress_advence = nil,
    txt_advence_state = nil,
    btn_advence_stop = nil,
    stc_advence_stopIcon = nil,
    btn_advence_Done = nil,
    stc_desc = nil
  },
  _ui_pc = {
    btn_question = nil,
    btn_close = nil,
    chk_popUp = nil,
    btn_restoreClose = nil,
    btn_restoreAll = nil,
    btn_repeatAll = nil
  },
  _ui_console = {
    stc_radioLB = nil,
    stc_radioRB = nil,
    stc_guideBg_normal = nil,
    stc_normal_restore = nil,
    stc_normal_repeat = nil,
    stc_normal_detail = nil,
    stc_normal_close = nil,
    stc_detailMenu = nil,
    txt_detailMenuTitle = nil,
    stc_menuBg = nil,
    btn_restore = nil,
    btn_repeatReset = nil,
    btn_workCancle = nil,
    btn_changeSkill = nil,
    btn_fire = nil,
    stc_guideBg_menu = nil,
    stc_menu_select = nil,
    stc_menu_close = nil
  },
  _workerGradeStr = {
    [0] = PAGetString(Defines.StringSheet_GAME, "LUA_WORKERMANAGER_WORKERGRADE_0"),
    [1] = PAGetString(Defines.StringSheet_GAME, "LUA_WORKERMANAGER_WORKERGRADE_1"),
    [2] = PAGetString(Defines.StringSheet_GAME, "LUA_WORKERMANAGER_WORKERGRADE_2"),
    [3] = PAGetString(Defines.StringSheet_GAME, "LUA_WORKERMANAGER_WORKERGRADE_3"),
    [4] = PAGetString(Defines.StringSheet_GAME, "LUA_WORKERMANAGER_WORKERGRADE_4"),
    [5] = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_FILTER_ALL")
  },
  _filterAllStr = PAGetString(Defines.StringSheet_GAME, "LUA_STABLEMARKET_FILTER_ALL"),
  _keyGuideA = {
    DETAIL = PAGetString(Defines.StringSheet_GAME, "LUA_WORKERMANAGER_CONSOLEGUIDE_DETAILMENU"),
    UPGRADE = PAGetString(Defines.StringSheet_RESOURCE, "PANEL_ARSHA_SUBMENU_UPGRADE"),
    COMPLETENOW = PAGetString(Defines.StringSheet_RESOURCE, "PANEL_STABLE_INFO_BTN_MATINGIMMEDIATELY")
  },
  _TAB = {
    WORKER = 1,
    UPGRADE = 2,
    COUNT = 2
  },
  _BUTTON = {
    STOP = 0,
    RESTORE = 1,
    FIRE = 2,
    CANCLE = 3,
    SKILL = 4,
    REPEAT = 5,
    UPGRADE = 6
  },
  _WORKTYPE = {
    HouseCraft = 0,
    LargeCraft = 1,
    PlantWork = 2,
    Building = 3,
    RegionWork = 4,
    Upgrade = 5,
    Harvest = 6
  },
  _radioTab = {},
  _selectTabIdx = nil,
  _plantArray = Array.new(),
  _workerArray = Array.new(),
  _townList = {},
  _gradeList = {},
  _selectFilterTown = -1,
  _selectFilterGrade = -1,
  _filteredArray = {},
  _totalWorkerCount = -1,
  _totalWorkerCapacity = -1,
  _listCnt = 0,
  _upgradingWorkerNoRaw = -1,
  _selectedRestoreWorkerIdx = 0,
  _restoreWorkerNo = nil,
  _restoreItemMaxCount = 7,
  _restoreItemHasCount = 0,
  _restoreItemSlot = {},
  _sliderStartIdx = 0,
  _elapsedTime = 0,
  _plantKey = nil,
  _lastTopIndex = 0,
  _detailBtnlist = {},
  _isConsole = false,
  _isPadSnap = false,
  _initialize = false
}
runLua("UI_Data/Script/Window/WorkerManager/Panel_WorkerManager_All_1.lua")
runLua("UI_Data/Script/Window/WorkerManager/Panel_WorkerManager_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_WorkerManager_All_Init")
function FromClient_WorkerManager_All_Init()
  PaGlobal_WorkerManager_All:initialize()
end
